/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __mars_message_DigitalDesc_hpp__
#define __mars_message_DigitalDesc_hpp__

#include <lcm/lcm_coretypes.h>

#include <string>

namespace mars_message
{

class DigitalDesc
{
    public:
        std::string desc;

        std::string on;

        std::string off;

#ifdef __NLOHMANN_JSON_CPP
    public:
        NLOHMANN_DEFINE_TYPE_INTRUSIVE(DigitalDesc, desc, on, off)
#endif
#ifdef __MSGPACK
    public:
        MSGPACK_DEFINE(DigitalDesc, desc, on, off)
#endif
    public:
        bool operator==(const DigitalDesc& other) const
        {
            return desc == other.desc && on == other.on && off == other.off;
        }
    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "DigitalDesc"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int DigitalDesc::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int DigitalDesc::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int DigitalDesc::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t DigitalDesc::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* DigitalDesc::getTypeName()
{
    return "DigitalDesc";
}

int DigitalDesc::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    char* desc_cstr = const_cast<char*>(this->desc.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &desc_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* on_cstr = const_cast<char*>(this->on.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &on_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* off_cstr = const_cast<char*>(this->off.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &off_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int DigitalDesc::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    int32_t __desc_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__desc_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__desc_len__ > maxlen - pos) return -1;
    this->desc.assign(
        static_cast<const char*>(buf) + offset + pos, __desc_len__ - 1);
    pos += __desc_len__;

    int32_t __on_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__on_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__on_len__ > maxlen - pos) return -1;
    this->on.assign(
        static_cast<const char*>(buf) + offset + pos, __on_len__ - 1);
    pos += __on_len__;

    int32_t __off_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__off_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__off_len__ > maxlen - pos) return -1;
    this->off.assign(
        static_cast<const char*>(buf) + offset + pos, __off_len__ - 1);
    pos += __off_len__;

    return pos;
}

int DigitalDesc::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->desc.size() + 4 + 1;
    enc_size += this->on.size() + 4 + 1;
    enc_size += this->off.size() + 4 + 1;
    return enc_size;
}

uint64_t DigitalDesc::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x9026e56a62ef3991LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
