"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct
import json

class DigitalDesc(object):
    __slots__ = ["desc", "on", "off"]

    __typenames__ = ["string", "string", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.desc = ""
        self.on = ""
        self.off = ""

    def encode(self):
        buf = BytesIO()
        buf.write(DigitalDesc._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __desc_encoded = self.desc.encode('utf-8')
        buf.write(struct.pack('>I', len(__desc_encoded)+1))
        buf.write(__desc_encoded)
        buf.write(b"\0")
        __on_encoded = self.on.encode('utf-8')
        buf.write(struct.pack('>I', len(__on_encoded)+1))
        buf.write(__on_encoded)
        buf.write(b"\0")
        __off_encoded = self.off.encode('utf-8')
        buf.write(struct.pack('>I', len(__off_encoded)+1))
        buf.write(__off_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != DigitalDesc._get_packed_fingerprint():
            raise ValueError("Decode error")
        return DigitalDesc._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = DigitalDesc()
        __desc_len = struct.unpack('>I', buf.read(4))[0]
        self.desc = buf.read(__desc_len)[:-1].decode('utf-8', 'replace')
        __on_len = struct.unpack('>I', buf.read(4))[0]
        self.on = buf.read(__on_len)[:-1].decode('utf-8', 'replace')
        __off_len = struct.unpack('>I', buf.read(4))[0]
        self.off = buf.read(__off_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if DigitalDesc in parents: return 0
        tmphash = (0x9026e56a62ef3991) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if DigitalDesc._packed_fingerprint is None:
            DigitalDesc._packed_fingerprint = struct.pack(">Q", DigitalDesc._get_hash_recursive([]))
        return DigitalDesc._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", DigitalDesc._get_packed_fingerprint())[0]

    def from_dict(self, j):
        self.desc = j["desc"]
        self.on = j["on"]
        self.off = j["off"]

    def to_dict(self):
        j = {}
        j["desc"] = self.desc
        j["on"] = self.on
        j["off"] = self.off
        return j

